/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cal_zodiaco;

import javax.swing.ImageIcon;

/**
 *
 * @author nicor
 */
public class fmhoroscopo extends javax.swing.JFrame {

        
    ImageIcon signo=new ImageIcon();
     
    /**
     *
     * Creates new form fmhoroscopo
     */
    public fmhoroscopo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btoncalcular = new javax.swing.JButton();
        btonuevo = new javax.swing.JButton();
        btonsalir = new javax.swing.JButton();
        txtdia = new javax.swing.JTextField();
        combomes = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar dia:");

        jLabel2.setText("Ingresar mes:");

        btoncalcular.setText("Calcular signo");
        btoncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoncalcularActionPerformed(evt);
            }
        });

        btonuevo.setText("Nuevo");
        btonuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonuevoActionPerformed(evt);
            }
        });

        btonsalir.setText("Salir");
        btonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsalirActionPerformed(evt);
            }
        });

        combomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Dieciembre" }));
        combomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomesActionPerformed(evt);
            }
        });

        resultado.setBorder(javax.swing.BorderFactory.createTitledBorder("TU ERES UN:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btoncalcular)
                            .addComponent(btonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btonuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combomes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btoncalcular)
                        .addGap(57, 57, 57)
                        .addComponent(btonuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btonsalir))
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomesActionPerformed

    private void btoncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoncalcularActionPerformed
        // TODO add your handling code here:
         //DECLARAMOS LAS VARIABLES Y USAMOS CONDICIONALES
         int dia=Integer.parseInt(txtdia.getText());
         String mes=(String)combomes.getSelectedItem();
         
         if(dia>=21 && mes.equals("Marzo")||dia<=20 && mes.equals("Abril")){
            resultado.setText("Aries");
         }else if (dia>=21 && mes.equals("Abril")||dia<=20 && mes.equals("Mayo")){
            resultado.setText("Tauro");
    }else if (dia>=21 && mes.equals("Mayo")|| dia<=21 &&mes.equals("Junio")){
            resultado.setText("Geminis");
    }else if (dia>=22&&mes.equals("Junio")|| dia<=22&&mes.equals("Julio")){
            resultado.setText("Cancer");
    }else if(dia>=23&&mes.equals("Julio")|| dia<=22&&mes.equals("Agosto")){
            resultado.setText("Leo");
    }else if(dia>=23&&mes.equals("Agosto")|| dia<=22&&mes.equals("Septiembre")){
            resultado.setText("Virgo");
    }else if(dia>=23&&mes.equals("Septiembre")|| dia<=22&&mes.equals("Octubre")){
            resultado.setText("Libra");
    }else if(dia>=23&&mes.equals("Octubre")|| dia<=21&&mes.equals("Noviembre")){
            resultado.setText("Escorpio");
    }else if (dia>=22&&mes.equals("Noviembre")|| dia<=21&&mes.equals("Diciembre")){
            resultado.setText("Sagitario");
    }else if(dia>=22&&mes.equals("Diciembre")|| dia<=20&&mes.equals("Enero")){
            resultado.setText("Capricornio");
    }else if(dia>=21&&mes.equals("Enero")|| dia<=19&&mes.equals("Febrero")){
            resultado.setText("Acuario");
    }else if(dia>=20&&mes.equals("Febrero")|| dia<=20&&mes.equals("Marzo")){
            resultado.setText("Piscis");
    }
         signo=new ImageIcon(getClass().getResource("/Imagenes/"+resultado.getText()+".jpg"));
            resultado.setIcon(signo);
            
        //    "/Imagenes/"+
         //      resultado.getText()
           //      +".jpg"
         
         //
           
    }//GEN-LAST:event_btoncalcularActionPerformed

    private void btonuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonuevoActionPerformed
        // TODO add your handling code here:
          txtdia.setText("");
         combomes.setSelectedIndex(0);
         resultado.setText("");
         resultado.setIcon(null);
    }//GEN-LAST:event_btonuevoActionPerformed

    private void btonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btonsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmhoroscopo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoncalcular;
    private javax.swing.JButton btonsalir;
    private javax.swing.JButton btonuevo;
    private javax.swing.JComboBox<String> combomes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField txtdia;
    // End of variables declaration//GEN-END:variables
}
